#!/usr/bin/env node
import * as lucide from 'lucide';
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

const ICON_NAMES = [
  'accessibility',
  'activity',
  'alarm-clock',
  'ambulance',
  'apple',
  'archive',
  'arrow-left',
  'award',
  'axe',
  'baby',
  'ban',
  'banknote',
  'bath',
  'battery',
  'bed',
  'bell',
  'bike',
  'bird',
  'blocks',
  'bluetooth',
  'book-open',
  'bookmark',
  'bot',
  'brain',
  'briefcase',
  'brush-cleaning',
  'bug',
  'building',
  'building-2',
  'bus',
  'cable',
  'calendar',
  'calendar-days',
  'camera',
  'car',
  'cat',
  'chart-bar',
  'chart-column',
  'chart-line',
  'check',
  'check-circle',
  'chef-hat',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'church',
  'circle',
  'circle-dollar-sign',
  'clapperboard',
  'clipboard',
  'clock',
  'cloud',
  'cloud-alert',
  'cloud-check',
  'code',
  'coffee',
  'component',
  'copy',
  'cpu',
  'cross',
  'crown',
  'database',
  'dog',
  'download',
  'download-cloud',
  'drama',
  'dumbbell',
  'earth',
  'edit-3',
  'factory',
  'fence',
  'file',
  'file-image',
  'file-text',
  'file-type',
  'film',
  'fingerprint',
  'fish',
  'flag',
  'flame',
  'flower',
  'flower-2',
  'folder',
  'funnel',
  'gamepad-2',
  'gift',
  'globe',
  'graduation-cap',
  'hammer',
  'hand-heart',
  'hand-helping',
  'handshake',
  'hard-drive',
  'headphones',
  'heart',
  'heart-handshake',
  'heart-pulse',
  'home',
  'hospital',
  'house-heart',
  'house-plus',
  'image',
  'inbox',
  'key-round',
  'keyboard',
  'land-plot',
  'landmark',
  'languages',
  'laptop',
  'layers',
  'layout-dashboard',
  'leaf',
  'life-buoy',
  'lightbulb',
  'link',
  'list',
  'list-todo',
  'lock-keyhole',
  'log-out',
  'mail',
  'map',
  'map-pin',
  'map-pinned',
  'mars',
  'menu',
  'message-circle',
  'mic',
  'monitor',
  'moon',
  'mountain',
  'music',
  'network',
  'newspaper',
  'notebook-pen',
  'package',
  'paintbrush',
  'palette',
  'paperclip',
  'paw-print',
  'pen-tool',
  'pencil',
  'person-standing',
  'phone',
  'pickaxe',
  'piggy-bank',
  'plane',
  'plug',
  'plus',
  'plus-square',
  'podcast',
  'presentation',
  'printer',
  'rabbit',
  'radio',
  'refresh-cw',
  'repeat',
  'rocket',
  'route',
  'scan-line',
  'school',
  'scissors',
  'search',
  'server',
  'settings',
  'share-2',
  'shield',
  'shield-check',
  'ship',
  'shopping-bag',
  'shopping-cart',
  'shovel',
  'shrub',
  'smartphone',
  'smile',
  'snail',
  'sofa',
  'sparkles',
  'spray-can',
  'sprout',
  'squirrel',
  'star',
  'stethoscope',
  'store',
  'sun',
  'tablet',
  'tag',
  'target',
  'tent',
  'terminal',
  'ticket',
  'tractor',
  'train',
  'trash',
  'trash-2',
  'tree-deciduous',
  'tree-pine',
  'trees',
  'triangle-alert',
  'truck',
  'turtle',
  'tv',
  'upload',
  'user',
  'user-plus',
  'users',
  'utensils',
  'venus', 'venus-and-mars',
  'volleyball',
  'wallet',
  'warehouse',
  'waves',
  'wifi',
  'worm',
  'wrench',
  'x',
  'zap',
];

const ICON_ALIASES = {
  'plus-square': 'square-plus',
  trash: 'trash-2',
};

function pascalCase(name) {
  const canonical = ICON_ALIASES[name] || name;
  return canonical.split('-').map(part => part.charAt(0).toUpperCase() + part.slice(1)).join('');
}

function attrsToString(attrs) {
  return Object.entries(attrs || {})
    .map(([key, value]) => ` ${key}=${JSON.stringify(String(value))}`)
    .join('');
}

function nodeToSvgPath(node) {
  const [tag, attrs] = node;
  return `<${tag}${attrsToString(attrs)}/>`;
}

const icons = {};
for (const name of ICON_NAMES) {
  const exportName = pascalCase(name);
  const iconNode = lucide[exportName];
  if (!iconNode) throw new Error(`Lucide export not found for ${name} (${exportName})`);
  icons[name] = iconNode.map(nodeToSvgPath).join('');
}

const sourceVersion = require('lucide/package.json').version;
const output = `// Generated from the lucide npm package. Do not edit by hand.\n// Run: npm run generate:icons\n// lucide version: ${sourceVersion}\n\nexport const LUCIDE_VERSION = ${JSON.stringify(sourceVersion)};\n\nexport const ICONS = ${JSON.stringify(icons, null, 2)};\n`;

writeFileSync('web/static/js/icons/lucide-generated.js', output);
console.log(`Generated ${Object.keys(icons).length} Lucide icons from lucide ${sourceVersion}`);
